services:
  traefik:
    image: traefik:v2.9.5
    container_name: traefik
    restart: unless-stopped
    env_file:
      - ./.env
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/services.yml:/services.yml:ro
      - /etc/acme.json:/acme.json
      - /usr/local/share/letsencrypt:/certificates
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.traefik-http.entrypoints=http"
      - "traefik.http.routers.traefik-http.rule=Host(`${DASHBOARD_HOST}`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-http.middlewares=traefik-https-redirect"

      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`${DASHBOARD_HOST}`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik-http.loadbalancer.server.port=888"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${DASHBOARD_USER}:${DASHBOARD_PASSWORD}"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
    networks:
      - "traefik"
  certsdump:
    image: ldez/traefik-certs-dumper:v2.10.0
    depends_on:
      - traefik
    entrypoint: sh -c 'apk add jq;
      while ! [ -e /data/acme.json ] || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ];
      do
      sleep 5;
      done &&
      traefik-certs-dumper file --version v2 --domain-subdir --clean=false --watch --source ./acme.json --dest .'
    volumes:
      - /usr/local/share/letsencrypt:/data
    working_dir: /data

networks:
  # Allow the use of traefik in other docker-compose.yml files
  traefik:
    external: true
#    enable_ipv6: true
#    ipam:
#      driver: default
#      config:
#        - subnet: 2001:3200:3200::/64
#          gateway: 2001:3200:3200::1